/* eslint-disable */

import { FunctionComponent } from 'react';
// Don't forget to install package: @types/react-native
import { ViewProps } from 'react-native';
import { GProps } from 'react-native-svg';

export { default as ISearch } from './ISearch';
export { default as IArrowUpDownCircle } from './IArrowUpDownCircle';
export { default as IParkings } from './IParkings';
export { default as IOrthodoxian } from './IOrthodoxian';
export { default as IShoppingMal } from './IShoppingMal';
export { default as IAirport } from './IAirport';
export { default as IAmbulance } from './IAmbulance';
export { default as IBank } from './IBank';
export { default as IChurch } from './IChurch';
export { default as IFactory } from './IFactory';
export { default as IFireStation } from './IFireStation';
export { default as IMuseum } from './IMuseum';
export { default as IPolice } from './IPolice';
export { default as ISchool } from './ISchool';
export { default as IUniversity } from './IUniversity';
export { default as ITheater } from './ITheater';
export { default as ISkyline } from './ISkyline';
export { default as IHouse } from './IHouse';
export { default as IBattery } from './IBattery';
export { default as IBike } from './IBike';
export { default as IBio } from './IBio';
export { default as IBiofuel } from './IBiofuel';
export { default as IBiohazard } from './IBiohazard';
export { default as ICo2 } from './ICo2';
export { default as IEcoHouse } from './IEcoHouse';
export { default as IEco } from './IEco';
export { default as IEcology } from './IEcology';
export { default as IElectricity } from './IElectricity';
export { default as IElectricCar } from './IElectricCar';
export { default as IGlobalWarming } from './IGlobalWarming';
export { default as IGreenEnergy } from './IGreenEnergy';
export { default as IHydroPower } from './IHydroPower';
export { default as IIndustry } from './IIndustry';
export { default as ILights } from './ILights';
export { default as INuclearPower } from './INuclearPower';
export { default as IRecycle } from './IRecycle';
export { default as ISolarPanels } from './ISolarPanels';
export { default as ISunEnergy } from './ISunEnergy';
export { default as ITurbine } from './ITurbine';
export { default as IWater } from './IWater';
export { default as IBlazeLine } from './IBlazeLine';
export { default as IFireLine } from './IFireLine';
export { default as IFlashlightLine } from './IFlashlightLine';
export { default as IMoneyEuroCircleLine } from './IMoneyEuroCircleLine';
export { default as IWaterFlashLine } from './IWaterFlashLine';
export { default as IEnergy } from './IEnergy';
export { default as IRiqi } from './IRiqi';
export { default as IZiliao } from './IZiliao';
export { default as IZixun } from './IZixun';
export { default as IBianxie } from './IBianxie';
export { default as IShouye } from './IShouye';
export { default as ICelsiusLine } from './ICelsiusLine';
export { default as ICloudy2Line } from './ICloudy2Line';
export { default as IBlazeFill } from './IBlazeFill';
export { default as IFlashlightFill } from './IFlashlightFill';
export { default as IFireFill } from './IFireFill';
export { default as IHome7Fill } from './IHome7Fill';
export { default as IHospitalFill } from './IHospitalFill';
export { default as ISendPlaneFill } from './ISendPlaneFill';
export { default as ISendPlaneLine } from './ISendPlaneLine';
export { default as IPieChart2Fill } from './IPieChart2Fill';
export { default as ILineChartLine } from './ILineChartLine';
export { default as ISlideshowFill } from './ISlideshowFill';
export { default as ICustomerServiceLine } from './ICustomerServiceLine';
export { default as IBallPenLine } from './IBallPenLine';
export { default as IQuillPenLine } from './IQuillPenLine';
export { default as IToolsFill } from './IToolsFill';
export { default as IBattery2ChargeFill } from './IBattery2ChargeFill';
export { default as IBatteryChargeFill } from './IBatteryChargeFill';
export { default as IBattery2ChargeLine } from './IBattery2ChargeLine';
export { default as IDashboard3Line } from './IDashboard3Line';
export { default as IDashboard3Fill } from './IDashboard3Fill';
export { default as IFingerprint2Line } from './IFingerprint2Line';
export { default as IFingerprintFill } from './IFingerprintFill';
export { default as IRadarFill } from './IRadarFill';
export { default as IWirelessChargingFill } from './IWirelessChargingFill';
export { default as IWirelessChargingLine } from './IWirelessChargingLine';
export { default as IExchangeFundsLine } from './IExchangeFundsLine';
export { default as IExchangeLine } from './IExchangeLine';
export { default as ICompassDiscoverLine } from './ICompassDiscoverLine';
export { default as ICompassLine } from './ICompassLine';
export { default as IMapPinLine } from './IMapPinLine';
export { default as IGaishuai } from './IGaishuai';
export { default as IFenlei } from './IFenlei';
export { default as IBianji } from './IBianji';
export { default as IXiaoxi } from './IXiaoxi';
export { default as IShanchu } from './IShanchu';
export { default as IDianpu } from './IDianpu';
export { default as IShezhi } from './IShezhi';
export { default as IFaxian } from './IFaxian';
export { default as IDingwei } from './IDingwei';
export { default as IXiazai } from './IXiazai';
export { default as IShenhe } from './IShenhe';
export { default as ILiaotian } from './ILiaotian';
export { default as INews } from './INews';
export { default as ISpeed } from './ISpeed';
export { default as IAEnergyResources } from './IAEnergyResources';
export { default as ILock } from './ILock';
export { default as IUser } from './IUser';

interface Props extends GProps, ViewProps {
  name: 'i-search' | 'i-arrow_up_down_circle' | 'i--parkings' | 'i--orthodoxian' | 'i--shopping-mal' | 'i-airport' | 'i-ambulance' | 'i-bank' | 'i-church' | 'i-factory' | 'i-fire-station' | 'i-museum' | 'i-police' | 'i-school' | 'i-university' | 'i-theater' | 'i--skyline' | 'i--house' | 'i-battery' | 'i-bike' | 'i-bio' | 'i-biofuel' | 'i-biohazard' | 'i-co2' | 'i-eco-house' | 'i-eco' | 'i-ecology' | 'i-electricity' | 'i-electric-car' | 'i-global-warming' | 'i-green-energy' | 'i-hydro-power' | 'i-industry' | 'i-lights' | 'i-nuclear-power' | 'i-recycle' | 'i-solar-panels' | 'i-sun-energy' | 'i-turbine' | 'i-water' | 'i-blaze-line' | 'i-fire-line' | 'i-flashlight-line' | 'i-money-euro-circle-line' | 'i-water-flash-line' | 'i-Energy' | 'i-riqi' | 'i-ziliao' | 'i-zixun' | 'i-bianxie' | 'i-shouye' | 'i-celsius-line' | 'i-cloudy-2-line' | 'i-blaze-fill' | 'i-flashlight-fill' | 'i-fire-fill' | 'i-home-7-fill' | 'i-hospital-fill' | 'i-send-plane-fill' | 'i-send-plane-line' | 'i-pie-chart-2-fill' | 'i-line-chart-line' | 'i-slideshow-fill' | 'i-customer-service-line' | 'i-ball-pen-line' | 'i-quill-pen-line' | 'i-tools-fill' | 'i-battery-2-charge-fill' | 'i-battery-charge-fill' | 'i-battery-2-charge-line' | 'i-dashboard-3-line' | 'i-dashboard-3-fill' | 'i-fingerprint-2-line' | 'i-fingerprint-fill' | 'i-radar-fill' | 'i-wireless-charging-fill' | 'i-wireless-charging-line' | 'i-exchange-funds-line' | 'i-exchange-line' | 'i-compass-discover-line' | 'i-compass-line' | 'i-map-pin-line' | 'i-gaishuai' | 'i-fenlei' | 'i-bianji' | 'i-xiaoxi' | 'i-shanchu' | 'i-dianpu' | 'i-shezhi' | 'i-faxian' | 'i-dingwei' | 'i-xiazai' | 'i-shenhe' | 'i-liaotian' | 'i-news' | 'i-speed' | 'i-a-EnergyResources' | 'i-lock' | 'i-user';
  size?: number;
  color?: string | string[];
}

declare const IconFont: FunctionComponent<Props>;

export default IconFont;
